### ISSUE TITLE
undefined method `sexp_type' for Array

### ISSUE THREAD

**Issue by patientdev** [jaredbeck/minitest_to_rspec#4]
I got the following error running `0.8.0` on a Rails controller spec. Spec source available on request.

Backtrace:
```
~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:180:in `rewrite': undefined method `sexp_type' for #<Array:0x00007f8800c20b48> (NoMethodError)
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:190:in `block (2 levels) in rewrite'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp.rb:65:in `map'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp.rb:65:in `map'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:190:in `block in rewrite'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:388:in `in_context'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:189:in `rewrite'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:190:in `block (2 levels) in rewrite'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp.rb:65:in `map'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp.rb:65:in `map'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:190:in `block in rewrite'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:388:in `in_context'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:189:in `rewrite'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sexp_processor-4.10.0/lib/sexp_processor.rb:226:in `process'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/minitest_to_rspec-0.8.0/lib/minitest_to_rspec/converter.rb:38:in `render'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/minitest_to_rspec-0.8.0/lib/minitest_to_rspec/converter.rb:16:in `convert'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/minitest_to_rspec-0.8.0/lib/minitest_to_rspec/cli.rb:57:in `run'
from ~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/minitest_to_rspec-0.8.0/bin/mt2rspec:3:in `<top (required)>'
from ~/.rbenv/versions/2.4.2/bin/mt2rspec:23:in `load'
from ~/.rbenv/versions/2.4.2/bin/mt2rspec:23:in `<main>'
```

**Comment by jaredbeck** [comment]
Looks like there were breaking changes in `sexp_processor` between 4.7 and 4.10. Fixed by 26d5654bc20 which applies a version constraint. Released as 0.9.0.

Thanks Shane.
